name: Auto-Deploy-Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6 # This is the action
        with:
          heroku_api_key: d74e9473-cd57-422b-9614-0f43740028f5
          heroku_app_name: "api-node-rocketseat" #Must be unique in Heroku
          heroku_email: "erykscarabello97@gmail.com"
